### ISSUE TITLE
Error running CAT, update_csv

### ISSUE THREAD

**Issue by felipeZ** [nlesc-nano/CAT#156]
When running CAT with the following input:
```yaml
path: "."

input_cores:
   - Cd68Se55.xyz:
        guess_bonds: False

input_ligands:
  - "smiles.txt"

optional:
    qd:
       bulkiness: True
    ligand:
           cosmo-rs: False
           functional_groups: ['O(C=O)[H]']
```
and `smiles.txt` files containing:
```
CCCCCCCCC=CCCCCCCCC(=O)O
CC(=O)O
O=C(O)Cc1ccccc1
CC(O)C(=O)O
```
I got the following error:
```
[10:37:38] INFO: Starting CAT (version: 0.9.9)
[10:37:38] INFO: The optional Nano-CAT package was successfully found (version: 0.6.1)
[10:37:38] INFO: The optional Data-CAT package was successfully found (version: 0.5.1)

[10:37:38] INFO: ligand_database.csv not found in /tmp/pytest-of-user/pytest-6/test_compute_bulkiness0/cat_workdir/0/database, creating ligand database
[10:37:38] INFO: qd_database.csv not found in /tmp/pytest-of-user/pytest-6/test_compute_bulkiness0/cat_workdir/0/database, creating qd database
[10:37:38] INFO: Updating h5py Dataset to data-CAT >= 0.4 style: 'core_no_opt'
[10:37:38] INFO: Updating h5py Dataset to data-CAT >= 0.4 style: 'ligand_no_opt'
[10:37:38] INFO: Updating h5py Dataset to data-CAT >= 0.4 style: 'qd_no_opt'
[10:37:39] CRITICAL: TypeError: update_csv() got multiple values for argument 'database'
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/insilico/bin/init_cat", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/envs/insilico/lib/python3.8/site-packages/CAT/data_handling/entry_points.py", line 64, in main
    raise ex
  File "/home/user/miniconda3/envs/insilico/lib/python3.8/site-packages/CAT/data_handling/entry_points.py", line 61, in main
    base.prep(extract_args(args), return_mol=False)
  File "/home/user/miniconda3/envs/insilico/lib/python3.8/site-packages/CAT/base.py", line 122, in prep
    ligand_df = prep_ligand(ligand_df)
  File "/home/user/miniconda3/envs/insilico/lib/python3.8/site-packages/CAT/base.py", line 296, in prep_ligand
    init_ligand_opt(ligand_df)
  File "/home/user/miniconda3/envs/insilico/lib/python3.8/site-packages/CAT/attachment/ligand_opt.py", line 68, in init_ligand_opt
    workflow.to_db(ligand_df, index=idx)
  File "/home/user/miniconda3/envs/insilico/lib/python3.8/site-packages/CAT/workflows/workflow.py", line 517, in to_db
    self.db.update_csv(
TypeError: update_csv() got multiple values for argument 'database'
```

**Comment by BvB93** [comment]
The issue is caused due to the absence of https://github.com/nlesc-nano/data-CAT/pull/45.
Updating data-CAT will resolve the problem.
